### ISSUE TITLE
name of YYY_Author_Template

### ISSUE THREAD

**Issue by teuben** [astroumd/ADASSProceedings#2]
PaperCheck.py is using Author_Template, not YYY_Author_Template.
But as distributed, we have a Makefile to easy the various building and checking.
Some users didn't see it that way and used their own directory.

My suggestion wold be they should make a symlink from Author_Template to YYYY_Author_Template.

So perhaps this needs to be sorrted out. In the mean time, we accepted a commit with this debatable patch.

**Comment by Bultako** [comment]
I'd be in favor of keeping the folder name Author_Template. The issue appeared because users got an `ADASS2020_Author_Template` folder instead of the year agnostic `Author_Template` when uncompressing the tar file. The only think we should take care of is to always work with a year agnostic Author_Template folder when producing the helping tar file every year. 

I have added a Note in bold in the Instructions for the proceedings of this year, to not change the name of this year agnostic folder. https://adass2020.es/proceedings/

So, I would revert the modif applied.
